### ISSUE TITLE
Main Menu broken on Pages and Posts when using Top--Bar with Customizer theme

### ISSUE THREAD

**Issue by icreationasia** [dannyvankooten/wp-mailchimp-top-bar#18]
Hi, love the plugin, but I just noticed that on every page other than the home page the Menu is deactivated when the top-bar plugin is enabled.  When I disable the plugin, the menu works again.
Have you had any other reports of the plugin disabling the Main menu?

**Comment by dannyvankooten** [comment]
Hi @icreationasia ,

This should be fixed in version 1.0.1 of [MailChimp Top Bar](https://wordpress.org/plugins/mailchimp-top-bar/), which I just pushed to WordPress.org. There should be an update available in your WP Admin.

Please update [MailChimp for WordPress](https://wordpress.org/plugins/mailchimp-for-wp/) first though. 

Hope that helps!

**Comment by icreationasia** [comment]
It does, thank you!

On Wed, Feb 4, 2015 at 11:39 PM, Danny van Kooten <notifications@github.com>
wrote:

> Hi @icreationasia <https://github.com/icreationasia> ,
>
> This should be fixed in version 1.0.1 of MailChimp Top Bar
> <https://wordpress.org/plugins/mailchimp-top-bar/>, which I just pushed
> to WordPress.org. There should be an update available in your WP Admin.
>
> Please update MailChimp for WordPress
> <https://wordpress.org/plugins/mailchimp-for-wp/> first though.
>
> Hope that helps!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dannyvankooten/wp-mailchimp-top-bar/issues/18#issuecomment-72876817>
> .
>



-- 
-- 
Tony Reno
Asia International Creation Limited
GPO Box 5377, Hong Kong China
*tony@icreation.asia <tony@icreation.asia>*
+852 98362432
Twitter: icreation_asia
