### ISSUE TITLE
Updating to 1.0.1 break plugin

### ISSUE THREAD

**Issue by ardenpm** [dannyvankooten/wp-mailchimp-top-bar#19]
After updating to 1.0.1 I receive the following message when trying to access the plugin settings:

```You do not have sufficient permissions to access this page.```

And the item no longer appears in the WP Mailchimp menu.

**Comment by dannyvankooten** [comment]
Hi @ardenpm ,

Sorry, this is a known issue which is why I just reverted the update. You're a quick updater! :)

For now you can fix it by reverting to v1.0: https://downloads.wordpress.org/plugin/mailchimp-top-bar.1.0.zip .

I will be pushing out an update of MailChimp for WordPress in an hour or so which fixes this. :+1:
